// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserData.Persistence.Context;

namespace UserData.Migrations
{
    [DbContext(typeof(UserDataContext))]
    [Migration("20200602190616_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserData.Core.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("UsersData");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Age = 2004422359,
                            FirstName = "3PXQUWGDBM1LC8PPD0J76JNURYKIBX3",
                            LastName = "UDHL524N2YI",
                            Street = "P9QRQXDB1SJOA82JINLJTG73YKD",
                            StreetNumber = 29
                        },
                        new
                        {
                            UserId = 2,
                            Age = 1326599063,
                            FirstName = "TBD86M7BN",
                            LastName = "V181DUK66EIBS7RRZRT8",
                            Street = "GV1SZ7AG",
                            StreetNumber = 29
                        },
                        new
                        {
                            UserId = 3,
                            Age = 281464760,
                            FirstName = "AEB4STFQOXQSPXRN6",
                            LastName = "21Q85KVFF7",
                            Street = "BXK248A4X5MAII3Y8",
                            StreetNumber = 14
                        },
                        new
                        {
                            UserId = 4,
                            Age = 534318416,
                            FirstName = "OHHF1Y752RAY8BFC",
                            LastName = "S6QZQOO7F6OU20W82",
                            Street = "2VT59MHE0WNTNNEQZT4L05G8CJ0J",
                            StreetNumber = 16
                        },
                        new
                        {
                            UserId = 5,
                            Age = 895362951,
                            FirstName = "5X142X83",
                            LastName = "IW1SL90O0GY06A6GIFSMTJOCNYE",
                            Street = "OVZHU7C4X14",
                            StreetNumber = 31
                        },
                        new
                        {
                            UserId = 6,
                            Age = 1650545284,
                            FirstName = "7UFK8X4XURPRJ8IZEW",
                            LastName = "1XUBJEU57IS6VAEM37C0REDVX9DC",
                            Street = "FOVMF87ZI7L",
                            StreetNumber = 12
                        },
                        new
                        {
                            UserId = 7,
                            Age = 1577766873,
                            FirstName = "U4QFVP1B",
                            LastName = "NXT8NKASYH97JSRM9JC6LZHYUDFX7",
                            Street = "VWCT2NT5GO26O",
                            StreetNumber = 22
                        },
                        new
                        {
                            UserId = 8,
                            Age = 671406043,
                            FirstName = "ZFUYP4OKFNU",
                            LastName = "6TOT3UCVER",
                            Street = "T0Y6JOFUF6DZPDKL92V",
                            StreetNumber = 26
                        },
                        new
                        {
                            UserId = 9,
                            Age = 944929782,
                            FirstName = "Z1SP0ABINED7U7RLZPD029M3DXUIB",
                            LastName = "EUYO1BKIO8ESAC6S5CNEB57DDZOZLCP",
                            Street = "RJQ23XE9F1OGAQPA5P1LA3",
                            StreetNumber = 26
                        },
                        new
                        {
                            UserId = 10,
                            Age = 431977661,
                            FirstName = "577IXUKBWV7LSMLWCMI",
                            LastName = "66DU31S40E20K76JR16Z5F4P",
                            Street = "9TJGGQARBFVJ9K7V2",
                            StreetNumber = 21
                        },
                        new
                        {
                            UserId = 11,
                            Age = 1578841180,
                            FirstName = "ELQT31CY",
                            LastName = "DFJ5N6HO",
                            Street = "I8NHUMCV94MO5CPKR3HAUP",
                            StreetNumber = 13
                        },
                        new
                        {
                            UserId = 12,
                            Age = 736453599,
                            FirstName = "2ISV98O7N6ZCYNEP8F9DV8RAJ3A",
                            LastName = "25719T72KLI8Z46",
                            Street = "PEMBWQ4MVM0B37I6E2J46GLLZ3U6UV",
                            StreetNumber = 30
                        },
                        new
                        {
                            UserId = 13,
                            Age = 451874311,
                            FirstName = "RLG7CER87CEPLEW7BO1CT3GFC",
                            LastName = "OKGGRMDB3ABAW0O9JASSJI94TE",
                            Street = "X8UNV1USH3",
                            StreetNumber = 18
                        },
                        new
                        {
                            UserId = 14,
                            Age = 1651947940,
                            FirstName = "LW5B1BXUTFWTRG",
                            LastName = "MXN6M5E4AFKAHHT",
                            Street = "YFB5LZH20V2L",
                            StreetNumber = 18
                        },
                        new
                        {
                            UserId = 15,
                            Age = 1597312866,
                            FirstName = "3T6PCI59OG156RA",
                            LastName = "M905MSI7NGARHI94V4",
                            Street = "97N8RMOEWFAO",
                            StreetNumber = 19
                        },
                        new
                        {
                            UserId = 16,
                            Age = 983082702,
                            FirstName = "S8KL9C6HO1GH6K",
                            LastName = "AUFVTTAE8",
                            Street = "1QG5IU0WCV5OYJF",
                            StreetNumber = 19
                        },
                        new
                        {
                            UserId = 17,
                            Age = 680085699,
                            FirstName = "ROTZ2T53TYW0R4M3X1L",
                            LastName = "KHGNLHG4P",
                            Street = "VFDT93VC5FFLZT8",
                            StreetNumber = 27
                        },
                        new
                        {
                            UserId = 18,
                            Age = 1891275687,
                            FirstName = "2WF7G14CIJ1BH5GQWEACG71Y",
                            LastName = "ON3G7YJ5KSUZX4CRV",
                            Street = "UUXU8VSBKJALH4UB3MX8I6FJHFOVNAO",
                            StreetNumber = 25
                        },
                        new
                        {
                            UserId = 19,
                            Age = 2056566139,
                            FirstName = "RT2OB5LVSF6MV09J8UVH2TJMB4I8",
                            LastName = "JT1XZIDCYQZNNW9E9N",
                            Street = "EBL888IALS5",
                            StreetNumber = 13
                        },
                        new
                        {
                            UserId = 20,
                            Age = 2096468978,
                            FirstName = "9QH24AWK",
                            LastName = "WLKCAHOM9KQZD21XC3WB9IKZWNZA",
                            Street = "B17XC7JPMGWMFIWEY6S5HKD53P6KHCR",
                            StreetNumber = 27
                        },
                        new
                        {
                            UserId = 21,
                            Age = 632825252,
                            FirstName = "OBUQXRNTZWHRCH23JAOSCASYLRBT",
                            LastName = "SQJ9GG7JMF0EOSE343QXMSGW",
                            Street = "JIBU8323IS7H1AL5XQF2HAI",
                            StreetNumber = 25
                        },
                        new
                        {
                            UserId = 22,
                            Age = 1686758414,
                            FirstName = "NYRN4RYV6MAJWJO2ONH9KLT",
                            LastName = "85M7O22VL8ME6EB",
                            Street = "S6FGP34GG7R5B5T74",
                            StreetNumber = 23
                        },
                        new
                        {
                            UserId = 23,
                            Age = 1072581593,
                            FirstName = "JMTRQNBFCUDQFLV4QWJ91ZCT1X371",
                            LastName = "XLHNH4HO6ZCAMOAKA29URBWKETJAZ2",
                            Street = "7SG6LIRJRG05MCEFP9E0GDUP7X6K",
                            StreetNumber = 20
                        },
                        new
                        {
                            UserId = 24,
                            Age = 240906551,
                            FirstName = "B8HQVZ6IXUHYDF8WIQIBIYI",
                            LastName = "PLCNNGWRJFSFGXLCMTQFQNXO8EEGJ",
                            Street = "E71J2D0XB0U60NXSQ",
                            StreetNumber = 18
                        },
                        new
                        {
                            UserId = 25,
                            Age = 872236319,
                            FirstName = "GYYIDQCYXPJ",
                            LastName = "PI31FQ5VB",
                            Street = "ZKBKXT4R8ZP7X3QV",
                            StreetNumber = 18
                        },
                        new
                        {
                            UserId = 26,
                            Age = 1746511546,
                            FirstName = "GSMU9D059J5YE86KVRNFDA",
                            LastName = "3BWOPZETX",
                            Street = "9H18Z0FXTBD00DW49W9DUPTQ",
                            StreetNumber = 15
                        },
                        new
                        {
                            UserId = 27,
                            Age = 736187653,
                            FirstName = "QTSMYLG4ZHO",
                            LastName = "PYSS7P2IJHD611M6FWS93O1JUH",
                            Street = "I2DU7M4140F5XC397FLS",
                            StreetNumber = 13
                        },
                        new
                        {
                            UserId = 28,
                            Age = 81144327,
                            FirstName = "7A6J70H1TNBUFYS8U",
                            LastName = "W3QTTS38WLDOGC3MFIRCTJS0",
                            Street = "6FS1DIOLQ9ZSK5JPWV78KZDZ",
                            StreetNumber = 25
                        },
                        new
                        {
                            UserId = 29,
                            Age = 1057906370,
                            FirstName = "9E5YFH912TKQSFNL03",
                            LastName = "K7QZ5DZE",
                            Street = "5R6P9ZBQ57ORO",
                            StreetNumber = 22
                        },
                        new
                        {
                            UserId = 30,
                            Age = 1991649253,
                            FirstName = "CUHUQDRSPAUQCO3N1TN5VIYXI0D31",
                            LastName = "0VSISMHGKAEBZVS",
                            Street = "10DWTEWCUKHDYNFSH",
                            StreetNumber = 11
                        },
                        new
                        {
                            UserId = 31,
                            Age = 494037602,
                            FirstName = "TCFESJTQZEPG8YQX4UAQL",
                            LastName = "LTGO82EAM3U0K3OHH0EJOF",
                            Street = "KLVVFLK46ULZAX0DK9835RGVJM1",
                            StreetNumber = 20
                        },
                        new
                        {
                            UserId = 32,
                            Age = 1634998497,
                            FirstName = "HFAOU21V",
                            LastName = "XQJRNB3JDOM7ZN",
                            Street = "GAT0ZMKJ71V8DL1LZ2WWINXIXNKM",
                            StreetNumber = 29
                        },
                        new
                        {
                            UserId = 33,
                            Age = 271751260,
                            FirstName = "NJ59DS2DK79OKFLOLJ",
                            LastName = "QH0U5NHJI0152260CH7EG3SI",
                            Street = "2NLDLC7HZVVTTT90PEFN0AV",
                            StreetNumber = 22
                        },
                        new
                        {
                            UserId = 34,
                            Age = 1156572673,
                            FirstName = "JHOFRXYR8M219P90OQ",
                            LastName = "XDNHLH7KF0UL8C4UTXL4RTF",
                            Street = "QK31BRLEIXZ9W6JTMSBHWO",
                            StreetNumber = 25
                        },
                        new
                        {
                            UserId = 35,
                            Age = 1370754429,
                            FirstName = "E7WURCXG277T",
                            LastName = "LTYTUNKE",
                            Street = "FKDM2W180L59C7TNS1OA3ZE4QCDV",
                            StreetNumber = 8
                        },
                        new
                        {
                            UserId = 36,
                            Age = 849571547,
                            FirstName = "HZ4RQ3NVF6SZLCDTK8QWR66HNOH0E",
                            LastName = "F8SO6KT4FHCUDAH440",
                            Street = "WAQFJ6ZTF2VOJOV5",
                            StreetNumber = 19
                        },
                        new
                        {
                            UserId = 37,
                            Age = 1837216603,
                            FirstName = "JQY3J9WR61CWP",
                            LastName = "NJWX8VY5TW",
                            Street = "QEIOK3XDCVXQ00UG6F29P3JT635ASTR",
                            StreetNumber = 29
                        },
                        new
                        {
                            UserId = 38,
                            Age = 1496929034,
                            FirstName = "QVN5V6TO7C7URFSJGTSB8DH50B",
                            LastName = "N246IV0AN",
                            Street = "Q8WUTDOGJC077SLCY0WD",
                            StreetNumber = 14
                        },
                        new
                        {
                            UserId = 39,
                            Age = 1509918781,
                            FirstName = "AQUKGG2HCNV",
                            LastName = "TAMYES5Y92UOOYFI4ENYHX2BW",
                            Street = "H51L93MPM32SHEC4MNRFU3GVDFY91F",
                            StreetNumber = 27
                        },
                        new
                        {
                            UserId = 40,
                            Age = 1932195530,
                            FirstName = "A6S6ILCLWID4N2PLCURMU630STEQ6O",
                            LastName = "A1Q1BU0NPPJ4XNL4E0VPQCA",
                            Street = "UFO18DWV0RUQ5QFI6G6RAUN",
                            StreetNumber = 17
                        },
                        new
                        {
                            UserId = 41,
                            Age = 217427022,
                            FirstName = "BN0LGB7LCFNGZ9ZK9G70BX82MZI34W",
                            LastName = "JJ7DN5DJB",
                            Street = "2OYGVOHUDC",
                            StreetNumber = 10
                        },
                        new
                        {
                            UserId = 42,
                            Age = 187353931,
                            FirstName = "GL5NP89R2EQPDE726",
                            LastName = "P675X8WANE0B71OY",
                            Street = "7OH8H6DH",
                            StreetNumber = 9
                        },
                        new
                        {
                            UserId = 43,
                            Age = 2012684288,
                            FirstName = "4KKGKTXLQKX61PU401HZAO",
                            LastName = "90GPS2EXY",
                            Street = "Z76D2I8W",
                            StreetNumber = 15
                        },
                        new
                        {
                            UserId = 44,
                            Age = 61882235,
                            FirstName = "SMICR17UPIKQEEESMX9U0JRAHA3V7HK",
                            LastName = "WH6GTCF7OQ04TDWI8U5DKTII4",
                            Street = "D4T0NDDH1JE",
                            StreetNumber = 13
                        },
                        new
                        {
                            UserId = 45,
                            Age = 1847944822,
                            FirstName = "OVXMLGOC8Y",
                            LastName = "LHY9C3R68JZAAVUV",
                            Street = "7LXI8U46H88KSBGJTXQ",
                            StreetNumber = 14
                        },
                        new
                        {
                            UserId = 46,
                            Age = 771270170,
                            FirstName = "Z99FTQWXOSU",
                            LastName = "2R1RO8R2HIS",
                            Street = "ZH11CMYK61G17TVXD3BDQC0R4ZUX11U",
                            StreetNumber = 23
                        },
                        new
                        {
                            UserId = 47,
                            Age = 996708861,
                            FirstName = "OZ8RVYN7CI3J",
                            LastName = "8QRMYJTI5M9O82P37844V2TUE5",
                            Street = "6N2BTFGAB8UQDX",
                            StreetNumber = 22
                        },
                        new
                        {
                            UserId = 48,
                            Age = 1123739277,
                            FirstName = "7DFJ8PGF76H3XB2FTISUZ4MZH91XJ",
                            LastName = "VBIYVMUT1RH6",
                            Street = "Z306OCVQH14D7TM9DW",
                            StreetNumber = 23
                        },
                        new
                        {
                            UserId = 49,
                            Age = 1199084377,
                            FirstName = "GD1PC9XT5",
                            LastName = "LGU8PQVARAN3G2ZJ2ZS5M5QGSS",
                            Street = "8GCFN30V",
                            StreetNumber = 22
                        },
                        new
                        {
                            UserId = 50,
                            Age = 262711552,
                            FirstName = "3G8AAOQ0NQ75QSYHZ2KT55UC4",
                            LastName = "TV5SEVWOXW",
                            Street = "23YA6I4NHWY23JUYN68",
                            StreetNumber = 28
                        },
                        new
                        {
                            UserId = 51,
                            Age = 1403276699,
                            FirstName = "UN9VVO58V5G744",
                            LastName = "5MLIC5CMB121143OB1JARSTAITZA",
                            Street = "S2DA1Y2L",
                            StreetNumber = 31
                        },
                        new
                        {
                            UserId = 52,
                            Age = 1022267152,
                            FirstName = "833XDD1R",
                            LastName = "FV3NM2LATFB",
                            Street = "X8JFOMTIPS",
                            StreetNumber = 16
                        },
                        new
                        {
                            UserId = 53,
                            Age = 1214083325,
                            FirstName = "WATYJRYOFZ4VOMPXW1L63DFQET",
                            LastName = "4I0CYV62A84TA2FURZ3H6DYLJ3",
                            Street = "E2SZPBRT3SQTZGUPVJSM7BE6",
                            StreetNumber = 31
                        },
                        new
                        {
                            UserId = 54,
                            Age = 2104348577,
                            FirstName = "X0KM41TP24W7KF5K3L8A",
                            LastName = "5T4ZNYATBT5",
                            Street = "5CU0Z3FOWG9RTOY2IKEX",
                            StreetNumber = 16
                        },
                        new
                        {
                            UserId = 55,
                            Age = 5206051,
                            FirstName = "RO8FXN2HQWRCT50L1VJ6TAPR7NF",
                            LastName = "HQFEPHBX",
                            Street = "MJN4BW93MNUJJ",
                            StreetNumber = 21
                        },
                        new
                        {
                            UserId = 56,
                            Age = 1526646192,
                            FirstName = "RNXM4D0B6XROHYE8KB8G4GED7UYDROO",
                            LastName = "F3J9L1K8JUCL44IKNJ9G23FL",
                            Street = "WPF21M8DECAW89MJQ9RIJH19",
                            StreetNumber = 13
                        },
                        new
                        {
                            UserId = 57,
                            Age = 1154606710,
                            FirstName = "2ICLN0HPI5",
                            LastName = "Y712MATVAUDBV45",
                            Street = "JPXURI3JOPEWS196J",
                            StreetNumber = 13
                        },
                        new
                        {
                            UserId = 58,
                            Age = 1379319348,
                            FirstName = "F0QKJTZHRRSRU82DO3ZMRBDQYXSC",
                            LastName = "XDN52LYLVV",
                            Street = "P265HPKL7C7NCA770RM",
                            StreetNumber = 24
                        },
                        new
                        {
                            UserId = 59,
                            Age = 1528879036,
                            FirstName = "AMEWAWWAXC3OEW1WD12HAWOGY6",
                            LastName = "4N4KEGV4PGBL9",
                            Street = "4PUQ3EH3S7",
                            StreetNumber = 31
                        },
                        new
                        {
                            UserId = 60,
                            Age = 1433609764,
                            FirstName = "Z1O878DO2X22YHS1LQCQ3HMUO",
                            LastName = "WQN260IOQ4QR",
                            Street = "AABP4BREC",
                            StreetNumber = 13
                        },
                        new
                        {
                            UserId = 61,
                            Age = 188290725,
                            FirstName = "RO4U1LWB90CTK0YK3H8IJALKF42TK",
                            LastName = "5YWS8PW7Q",
                            Street = "UHAJIL37CZBBV",
                            StreetNumber = 26
                        },
                        new
                        {
                            UserId = 62,
                            Age = 1270096565,
                            FirstName = "75N611IY60HX02BCQ2ZKSGBVJ",
                            LastName = "RMCTTHS2KO42JLAE9C506ZBR7E32I",
                            Street = "HKHYBDI263DNWRDTO7TD",
                            StreetNumber = 25
                        },
                        new
                        {
                            UserId = 63,
                            Age = 1797621946,
                            FirstName = "OOZUUUCENAESW55V8HOIIV",
                            LastName = "S3T5CD6SU912VPO7CG",
                            Street = "X6K5VNH9E8RXIYSOKOG80T92LV",
                            StreetNumber = 21
                        },
                        new
                        {
                            UserId = 64,
                            Age = 319960576,
                            FirstName = "ABQSTT4DKFUKLCYQCM892HE5",
                            LastName = "XWO8WHX6NGSY4WMZ9U2QJVLYM651B6",
                            Street = "F5UC48BU6NM38H0A",
                            StreetNumber = 26
                        },
                        new
                        {
                            UserId = 65,
                            Age = 1952668238,
                            FirstName = "CL0V0M65RNVDJ0PJ464U5XP",
                            LastName = "VYFG1DFUF63VZS7VASQ",
                            Street = "U57QEX86O75G1H0VJ3XMP",
                            StreetNumber = 19
                        },
                        new
                        {
                            UserId = 66,
                            Age = 1246398116,
                            FirstName = "TL9IUNH7670F90EOCLEOZQS4OKO",
                            LastName = "JTZUBMQX0",
                            Street = "79GA80R42O6IACHZEOIB8N7",
                            StreetNumber = 14
                        },
                        new
                        {
                            UserId = 67,
                            Age = 570969846,
                            FirstName = "4K8FYMHFDWJ",
                            LastName = "X3BZG0EPTMTA1PVDMSJ",
                            Street = "H8LCLB0NJ48WITDD3",
                            StreetNumber = 17
                        },
                        new
                        {
                            UserId = 68,
                            Age = 1775458820,
                            FirstName = "8OJ1E3VN6XBPCKFQFUNOQ69IR",
                            LastName = "4F6PPA7IRXBH0NM0HFFZ",
                            Street = "O9PBK95G7DD2GEUSMM8OVR",
                            StreetNumber = 19
                        },
                        new
                        {
                            UserId = 69,
                            Age = 499449596,
                            FirstName = "RQHAS42RO849C0Y3D1",
                            LastName = "V89XV248",
                            Street = "623ICKBPAKW9",
                            StreetNumber = 18
                        },
                        new
                        {
                            UserId = 70,
                            Age = 491361159,
                            FirstName = "XPZR49IATNV7",
                            LastName = "VNQR3VIX5NJOA0VER768",
                            Street = "7DO7I17E",
                            StreetNumber = 21
                        },
                        new
                        {
                            UserId = 71,
                            Age = 778504071,
                            FirstName = "AQ17L6T2CPD3JW5CPY87",
                            LastName = "HH8A9X4QKWKVI",
                            Street = "JS2WU3OCXDP",
                            StreetNumber = 22
                        },
                        new
                        {
                            UserId = 72,
                            Age = 1463768140,
                            FirstName = "232HBBHMPD66XEOT",
                            LastName = "W06DXXFE8",
                            Street = "9VCBUD3P9M78MW8FRJ3I26LIZ",
                            StreetNumber = 26
                        },
                        new
                        {
                            UserId = 73,
                            Age = 957394083,
                            FirstName = "CJ1PM3CUP3",
                            LastName = "7KL3FDQ26UMCWXHUL",
                            Street = "CJ3LILAW1L609G5IUVZ3J5YS3IEFX",
                            StreetNumber = 20
                        },
                        new
                        {
                            UserId = 74,
                            Age = 12188591,
                            FirstName = "PLUNYYEXN0T0GE1FI1CPWT7WCGFTW",
                            LastName = "ZUGGGMXGW45TRJESQ42Y3P71J",
                            Street = "49XIX9U4CG9G",
                            StreetNumber = 29
                        },
                        new
                        {
                            UserId = 75,
                            Age = 848968482,
                            FirstName = "K7Z5ELLS3IF8R6MH1KZHG4ZO12I2D1",
                            LastName = "LECXR1G96HUHPMVINP0E98H0Q",
                            Street = "LSSUAXA8T98PRBEITDBYSUZK176KXP",
                            StreetNumber = 13
                        },
                        new
                        {
                            UserId = 76,
                            Age = 655705419,
                            FirstName = "PVL29VWJCFT5NMW0M7LHJQBX4ZFF",
                            LastName = "R13EUKTYGHF48I83HFCP2S6DBU9TX8",
                            Street = "MCSPCS43PI",
                            StreetNumber = 14
                        },
                        new
                        {
                            UserId = 77,
                            Age = 951269210,
                            FirstName = "ZF95ZD9L9A",
                            LastName = "6ZNWYVCRMAL0M",
                            Street = "MUN002CDBG0GMLHC4WU",
                            StreetNumber = 11
                        },
                        new
                        {
                            UserId = 78,
                            Age = 1985548143,
                            FirstName = "FIDOOXZ2O0USH6GMWODDC3TJHZ",
                            LastName = "MPZUH8BFRJM271HJC",
                            Street = "J1Q3L0M0HURAX20EA83R8ZTR",
                            StreetNumber = 12
                        },
                        new
                        {
                            UserId = 79,
                            Age = 1276849478,
                            FirstName = "4URCW6LZLNJ0UM4",
                            LastName = "PGDXO5U64BXL7BBYKD40H1U27XB",
                            Street = "BWEMKQOYLY4GZJNMYGMTF0YDKWF",
                            StreetNumber = 14
                        },
                        new
                        {
                            UserId = 80,
                            Age = 1926185146,
                            FirstName = "DVXVKZ14K9IB4PCN7F2G",
                            LastName = "0WT9T7518KFSK2KASH1FFZVASPU0",
                            Street = "9365YDSR69AUIUJA2JMVQR",
                            StreetNumber = 29
                        },
                        new
                        {
                            UserId = 81,
                            Age = 836416864,
                            FirstName = "7AA0BBSRDME5U3SHXQ",
                            LastName = "56Q9JDN578588S8",
                            Street = "XLXM8EV125CLZCTTW1N",
                            StreetNumber = 20
                        },
                        new
                        {
                            UserId = 82,
                            Age = 1316150823,
                            FirstName = "RTRB0XXGVSHOGMWK66",
                            LastName = "FOK22US6WANV93SBPBUTKX0AV",
                            Street = "7L6VEXP0G15UM6F",
                            StreetNumber = 18
                        },
                        new
                        {
                            UserId = 83,
                            Age = 88410020,
                            FirstName = "GJLMPSXKGMS8DQP",
                            LastName = "F33Q4YMDMUWV1ZHQ5S8LLD0RN",
                            Street = "3FUXQG9BG0ZRH0BFI6IVY",
                            StreetNumber = 29
                        },
                        new
                        {
                            UserId = 84,
                            Age = 1230148008,
                            FirstName = "CSRECCVRDOBCLC8D9FD7B4J82YXBQ",
                            LastName = "DD5VLODI6GADXEZNQF",
                            Street = "8JWU0S1P1IQS6HA5",
                            StreetNumber = 20
                        },
                        new
                        {
                            UserId = 85,
                            Age = 890575287,
                            FirstName = "TBRBG71CFU6S1RB940G1",
                            LastName = "8OG2AB6BDJ7F69AGI",
                            Street = "C784IISMNOTBYK8GZ1TA0J668GFIPH",
                            StreetNumber = 26
                        },
                        new
                        {
                            UserId = 86,
                            Age = 557382058,
                            FirstName = "8720U9MB5W9321YZ2OO4AW",
                            LastName = "DWLE4OK85OZTLXNA",
                            Street = "YNP41FP6HLSIQDVWLIF54BCK9M4RB3",
                            StreetNumber = 23
                        },
                        new
                        {
                            UserId = 87,
                            Age = 2065053122,
                            FirstName = "LTZDJ5RWUXEPCINBPO163M",
                            LastName = "IPAVT1J5IP",
                            Street = "KJ4HKTKXBCX8",
                            StreetNumber = 11
                        },
                        new
                        {
                            UserId = 88,
                            Age = 465946445,
                            FirstName = "K2597AVDFY9PJWRSW3KWGXIMNMIL",
                            LastName = "VSRSZP342KKLSQ95WTM8",
                            Street = "8K01QU0V02HK7VWX5C29QQYIK8",
                            StreetNumber = 30
                        },
                        new
                        {
                            UserId = 89,
                            Age = 97724827,
                            FirstName = "4SALXGIQ035MUTCRH91JLFZ",
                            LastName = "A763N09FKJH69ABRLC61",
                            Street = "9LZXUSWV1KUTFS6THX",
                            StreetNumber = 29
                        },
                        new
                        {
                            UserId = 90,
                            Age = 2046722234,
                            FirstName = "3RKZJODA40BKMFRG8J7JJ7WC",
                            LastName = "70LAPZ67SDRZMI7857F6ZX8TSVGQCP",
                            Street = "9DBZTQOM",
                            StreetNumber = 29
                        },
                        new
                        {
                            UserId = 91,
                            Age = 1872510509,
                            FirstName = "BALNAQFHK21R3SQ5CHWRT5",
                            LastName = "F6RE1N25UB9FP",
                            Street = "2MY29PBEM4C9R",
                            StreetNumber = 25
                        },
                        new
                        {
                            UserId = 92,
                            Age = 108738693,
                            FirstName = "NAEBMHP83MFN5WD6ABGC69XUULC",
                            LastName = "1UA2C2EXM0RFUDLPADXZJ7R4",
                            Street = "OCVC6ASVSYR14N9CF1FRTMN3R6HQ",
                            StreetNumber = 8
                        },
                        new
                        {
                            UserId = 93,
                            Age = 840706747,
                            FirstName = "2Y5ZK2KQ946",
                            LastName = "CY2TH4NHK",
                            Street = "OMTQAF0HJMMLDSPUJUBR3XITQYMO3D",
                            StreetNumber = 31
                        },
                        new
                        {
                            UserId = 94,
                            Age = 1940610355,
                            FirstName = "XI2F19DCX6VF5YEFUQ653",
                            LastName = "09G2JEGTS76EELPZVHG7JHF8EL",
                            Street = "0E9AM3LNFG",
                            StreetNumber = 13
                        },
                        new
                        {
                            UserId = 95,
                            Age = 1435849496,
                            FirstName = "T3IX86S2UXUOI3V0WSGB",
                            LastName = "3RZO2O84DUW",
                            Street = "7JL05R389Z95EOXJ0T3Z54YZ5",
                            StreetNumber = 28
                        },
                        new
                        {
                            UserId = 96,
                            Age = 819425169,
                            FirstName = "T45WAK0DY39RACRO4Z4ODAAHWHCVV2M",
                            LastName = "7Z3QERF7POFT05S",
                            Street = "90L1DML3AYML9DFIGS4N0MSJFRU8RC",
                            StreetNumber = 12
                        },
                        new
                        {
                            UserId = 97,
                            Age = 1486203244,
                            FirstName = "ER5RYTKIAKMU7",
                            LastName = "Z4RQ1Y46SCDYJ5KVQRMYK6JBCLI8Y2N",
                            Street = "0JWY4S4Y92",
                            StreetNumber = 24
                        },
                        new
                        {
                            UserId = 98,
                            Age = 1530950723,
                            FirstName = "QQ6IZZN9TZXJJJIKC",
                            LastName = "QXDA2AJ7RRRBNC721XS9JEAA0ZKFVV",
                            Street = "FXMHHDOI93O9KP8O45HIX2VP",
                            StreetNumber = 31
                        },
                        new
                        {
                            UserId = 99,
                            Age = 2032642150,
                            FirstName = "XCJDZDM6RSQS7ERL",
                            LastName = "W9R6DSIN03FDOFSH2EIGUF6PLO9C4XH",
                            Street = "5F2LQX591H6SSMUMQSU2DX",
                            StreetNumber = 31
                        },
                        new
                        {
                            UserId = 100,
                            Age = 424442090,
                            FirstName = "CVYTGSCWG6",
                            LastName = "9OBNUYF4GWISLVETSG0CGZ9D34B",
                            Street = "GDFPTUB09JH2CN8KEAIEOQ",
                            StreetNumber = 28
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
