// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserData.Persistence.Context;

namespace UserData.Migrations
{
    [DbContext(typeof(UserDataContext))]
    [Migration("20200605103500_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserData.Core.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UsersData");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Age = 129382961,
                            FirstName = "AK6IMI8UTM9IHPGBG63PI51O2CDA2OA",
                            LastName = "XPIVD1ZAFLD",
                            Street = "D5WTZLFI0JAZY7",
                            StreetNumber = 12,
                            TelephoneNumber = "709852888"
                        },
                        new
                        {
                            UserId = 2,
                            Age = 1120289172,
                            FirstName = "KRVUHKFYDCV",
                            LastName = "P5HU856SFW8JPVC",
                            Street = "FTRQJE71EL3U2GV8PH2J61UYZ",
                            StreetNumber = 13,
                            TelephoneNumber = "839871841"
                        },
                        new
                        {
                            UserId = 3,
                            Age = 1241971615,
                            FirstName = "3Y2G9XTLEWH64ZD1",
                            LastName = "KB1NN1MDATP6L3FGRUJAU",
                            Street = "TPECSNE17C",
                            StreetNumber = 11,
                            TelephoneNumber = "198443523"
                        },
                        new
                        {
                            UserId = 4,
                            Age = 863068366,
                            FirstName = "44S7JAT1GBL",
                            LastName = "MI5SEMURGC2PWZJ45IU4UMBQQR",
                            Street = "TR6L9P7QC8DDP32CZNF419",
                            StreetNumber = 23,
                            TelephoneNumber = "452901048"
                        },
                        new
                        {
                            UserId = 5,
                            Age = 1778693994,
                            FirstName = "UJQAAIDXCNJPMHD",
                            LastName = "3L8WX5PWP3N1BT9WL20KJZ50N",
                            Street = "ARGR81BDKU0Z58QRG9HOBXZE89F0",
                            StreetNumber = 27,
                            TelephoneNumber = "169964641"
                        },
                        new
                        {
                            UserId = 6,
                            Age = 1409009311,
                            FirstName = "EUR2PDQII403ZPE7FWNMPHE",
                            LastName = "QPEY5CGV",
                            Street = "EXZ33VG5LWTN",
                            StreetNumber = 13,
                            TelephoneNumber = "281989029"
                        },
                        new
                        {
                            UserId = 7,
                            Age = 1865904570,
                            FirstName = "WMEQLLBQL8V76GQG",
                            LastName = "70SR9CPV",
                            Street = "8AEFC7FAFBI7PQM991NGXFUPU98",
                            StreetNumber = 24,
                            TelephoneNumber = "184750983"
                        },
                        new
                        {
                            UserId = 8,
                            Age = 1718955588,
                            FirstName = "2XJJMWDVK",
                            LastName = "JFOZEBL84",
                            Street = "1VDO6YAFPKRZOOWJQ4XJZ5XFIAVNS8",
                            StreetNumber = 20,
                            TelephoneNumber = "975289918"
                        },
                        new
                        {
                            UserId = 9,
                            Age = 190376311,
                            FirstName = "CEBNOX7ZHO",
                            LastName = "YGAC6GXHFYMK2GZSB52H9B",
                            Street = "XRHYBEEKWNJNIPZJPE9KPYP",
                            StreetNumber = 10,
                            TelephoneNumber = "590789451"
                        },
                        new
                        {
                            UserId = 10,
                            Age = 1740291949,
                            FirstName = "IZEHR9EWD92ZPS1Y5D4UH4UZ1V",
                            LastName = "P997KYAIUKSM",
                            Street = "BCOCDD2QKPZ3IGZE54OHWWCPF2P",
                            StreetNumber = 14,
                            TelephoneNumber = "000906718"
                        },
                        new
                        {
                            UserId = 11,
                            Age = 861634904,
                            FirstName = "VSE3XXC2CUVP5M3Q5P5CPQLQ64",
                            LastName = "XO4YAHKMLPUR1ND0FAZGF",
                            Street = "B84UNEPP63ZWEBRBOJGNM",
                            StreetNumber = 13,
                            TelephoneNumber = "947523116"
                        },
                        new
                        {
                            UserId = 12,
                            Age = 1988022413,
                            FirstName = "8GE1WYX9ZTJPRUF06D2PU9QBI0EZ87",
                            LastName = "8DKW3MJXKP0WF69YEIZTMFCM9Z",
                            Street = "DOOH6VHVARAK8DZMZGPGYOPQQ7R",
                            StreetNumber = 10,
                            TelephoneNumber = "585907733"
                        },
                        new
                        {
                            UserId = 13,
                            Age = 458713478,
                            FirstName = "WRG6L66XCSXO9J4UR0ONRL",
                            LastName = "LHF6Y1RER8TWU3",
                            Street = "LOXPR94MLEJBAQJNO3B7WDI010R04M",
                            StreetNumber = 21,
                            TelephoneNumber = "945194972"
                        },
                        new
                        {
                            UserId = 14,
                            Age = 1048731425,
                            FirstName = "5P0UREA8QLN853RKJNB3",
                            LastName = "35XQDITE19LTGJ",
                            Street = "GA9Q9DLG5YF9I6VNFQPWJ07165MM5L",
                            StreetNumber = 21,
                            TelephoneNumber = "431214938"
                        },
                        new
                        {
                            UserId = 15,
                            Age = 1629002253,
                            FirstName = "DEN6R4YMCPYT627J2Y24T",
                            LastName = "ZBJETY9RC7IAOH0MXWK93MNPS2",
                            Street = "8PVD93RIB",
                            StreetNumber = 12,
                            TelephoneNumber = "707420343"
                        },
                        new
                        {
                            UserId = 16,
                            Age = 1371230683,
                            FirstName = "MY4V0SKQJRAAD2OZKKKXI8WEWOQGU1K",
                            LastName = "PMCY21VRBDDJK5K6E105I7ZN",
                            Street = "LAMUN0K6NZSQBGTU",
                            StreetNumber = 9,
                            TelephoneNumber = "793019413"
                        },
                        new
                        {
                            UserId = 17,
                            Age = 1245882411,
                            FirstName = "8HVC7LTGO5GGQLUSY5",
                            LastName = "HRBDQ27CEBD32Q",
                            Street = "006TZ2VE5M40ETC2BOPSWYWC1J",
                            StreetNumber = 16,
                            TelephoneNumber = "692284536"
                        },
                        new
                        {
                            UserId = 18,
                            Age = 1988482005,
                            FirstName = "WENGVU76D6GWKON04D95GGHN5QS5",
                            LastName = "O5SHXP3S6UZDMLJEPDL",
                            Street = "I9GBF7HRB86DFKAIOFKBOZDYXJO9",
                            StreetNumber = 25,
                            TelephoneNumber = "981416490"
                        },
                        new
                        {
                            UserId = 19,
                            Age = 653710571,
                            FirstName = "TJ2448IQNHFTVZDEA86RVPYB7WJQAQ",
                            LastName = "GZ5WEL2V8141464D",
                            Street = "BBOYAXOW9TI",
                            StreetNumber = 14,
                            TelephoneNumber = "526067315"
                        },
                        new
                        {
                            UserId = 20,
                            Age = 1621323561,
                            FirstName = "STU5OJ9P597ANHVRPXY9U",
                            LastName = "1W3Y06YCSO4FUPIL8Y",
                            Street = "HZ2P6484ZD83HM801X4EDT8604LU9",
                            StreetNumber = 25,
                            TelephoneNumber = "378101722"
                        },
                        new
                        {
                            UserId = 21,
                            Age = 856845508,
                            FirstName = "7P1S8VPX4S4GSXLJIFXV9NX",
                            LastName = "7FEAJ9501O4RLHTRKFWALCDT65Q3V",
                            Street = "599C17C0SD02QTGIWGIEY9JI",
                            StreetNumber = 23,
                            TelephoneNumber = "657868443"
                        },
                        new
                        {
                            UserId = 22,
                            Age = 1813576258,
                            FirstName = "LZQV09512NHX91D7PHPL22GJ01",
                            LastName = "K9KU9KMRERP5GPD8INHC3AQE4Z28ST",
                            Street = "DPD238BWGL40WV4CUEOTCEE",
                            StreetNumber = 12,
                            TelephoneNumber = "890574823"
                        },
                        new
                        {
                            UserId = 23,
                            Age = 1362841023,
                            FirstName = "GZJSO8VKU5D3MROE5PTC",
                            LastName = "ESQ6IYVL",
                            Street = "8Q9MJ6Z476SYDJ",
                            StreetNumber = 15,
                            TelephoneNumber = "393221982"
                        },
                        new
                        {
                            UserId = 24,
                            Age = 650746995,
                            FirstName = "VFKA9IUESDGLFBHIY5YBL35LCTY",
                            LastName = "PEZI6FICA",
                            Street = "FPQFCNMS1XITHSCH",
                            StreetNumber = 16,
                            TelephoneNumber = "119052126"
                        },
                        new
                        {
                            UserId = 25,
                            Age = 1337535289,
                            FirstName = "7PURZOO7PA2EILYRFKJWE48BBEVC50X",
                            LastName = "2AP1WPLF5I2V36CH85",
                            Street = "KSXNFS2K",
                            StreetNumber = 8,
                            TelephoneNumber = "256804545"
                        },
                        new
                        {
                            UserId = 26,
                            Age = 1734099075,
                            FirstName = "IFCNDAZP7EFNJE9Z",
                            LastName = "TGDIRT3MBALIO789",
                            Street = "CYMMMI575Z9D16C",
                            StreetNumber = 11,
                            TelephoneNumber = "225420994"
                        },
                        new
                        {
                            UserId = 27,
                            Age = 488020456,
                            FirstName = "1VIBC9NHTH",
                            LastName = "NF40H7LDDLCL",
                            Street = "SX0ZJ1H09",
                            StreetNumber = 26,
                            TelephoneNumber = "832596720"
                        },
                        new
                        {
                            UserId = 28,
                            Age = 50489909,
                            FirstName = "KQHY02I5R8MELC6TFBRWGK5Z",
                            LastName = "NV633VFJ3N3GRM3RAT62NT7GK0VN",
                            Street = "XKNFCVZ5B5ES59C36W51",
                            StreetNumber = 11,
                            TelephoneNumber = "595583130"
                        },
                        new
                        {
                            UserId = 29,
                            Age = 1445122705,
                            FirstName = "0TCA1DKNIYX9WF95TUSBID7C",
                            LastName = "ZANIWULSTVRVMP2HL4YAZC9G5OM92",
                            Street = "H5SYCMYZYEF187R3",
                            StreetNumber = 18,
                            TelephoneNumber = "660100916"
                        },
                        new
                        {
                            UserId = 30,
                            Age = 202478344,
                            FirstName = "MHIM0D95UHNZ",
                            LastName = "GIVYI9PZWHGJ8S",
                            Street = "QDTRJHF037JIBGXB",
                            StreetNumber = 16,
                            TelephoneNumber = "399407738"
                        },
                        new
                        {
                            UserId = 31,
                            Age = 14176930,
                            FirstName = "9YTO30XS95D6HP",
                            LastName = "P2LZVA0PJBN27",
                            Street = "9UWZ91AT0BXN7YVR0ABD1UWRV",
                            StreetNumber = 30,
                            TelephoneNumber = "491077303"
                        },
                        new
                        {
                            UserId = 32,
                            Age = 465217671,
                            FirstName = "PD26UBY5HVGCWWXMDP",
                            LastName = "C081884E3PAK876MH8DZ",
                            Street = "ZPZ0O32W4M2K19JIJJNP80UU683RX6",
                            StreetNumber = 13,
                            TelephoneNumber = "531876992"
                        },
                        new
                        {
                            UserId = 33,
                            Age = 1310096969,
                            FirstName = "6HK6HU3KI3DI55EG9LZ69UTTIX",
                            LastName = "I0L3MKYOWW3YKX5BNBQOVJ2191",
                            Street = "CE4YRL37Z64QGKHEZJQN90LRN",
                            StreetNumber = 19,
                            TelephoneNumber = "736765755"
                        },
                        new
                        {
                            UserId = 34,
                            Age = 1968107261,
                            FirstName = "JDTGR2JH87U3V46C94",
                            LastName = "FSBLENKTHE0",
                            Street = "07GQSUGW",
                            StreetNumber = 13,
                            TelephoneNumber = "533167428"
                        },
                        new
                        {
                            UserId = 35,
                            Age = 628559705,
                            FirstName = "Z8PIWHKSVJ47P",
                            LastName = "1GFP70ISU6P96NYCWJRO8N16",
                            Street = "WXMHFDKNSZBR7H2P2HJBC",
                            StreetNumber = 18,
                            TelephoneNumber = "010176971"
                        },
                        new
                        {
                            UserId = 36,
                            Age = 1393831670,
                            FirstName = "WHN2KPG20BA3FFO19ID22HHVEBU2",
                            LastName = "JH33JZ23VJORSG1S3",
                            Street = "B3DM9GOT3XK63SWVPA0NOI9",
                            StreetNumber = 18,
                            TelephoneNumber = "269411104"
                        },
                        new
                        {
                            UserId = 37,
                            Age = 2145351278,
                            FirstName = "AYWGK2B7ATDEZ7L3T49ABHQ52NUY",
                            LastName = "XUH9V3SMZF36P8EI",
                            Street = "XJ4OOQ4G96PW8N8YLJBPDLVKGP",
                            StreetNumber = 11,
                            TelephoneNumber = "357504138"
                        },
                        new
                        {
                            UserId = 38,
                            Age = 1727804660,
                            FirstName = "Q3ZFEVJMXXCC64VDAU1ALVLIVT3",
                            LastName = "EM9HN9BI1BKIT5E04FQ105",
                            Street = "1O6IMVM95FDE",
                            StreetNumber = 28,
                            TelephoneNumber = "531484455"
                        },
                        new
                        {
                            UserId = 39,
                            Age = 1658925391,
                            FirstName = "5JSG0KRZQ6X3C9RT9N",
                            LastName = "6J2XBN6CEQZ182I8PPVW",
                            Street = "HKY4Y72NM8KTQQRVOPDC5IR",
                            StreetNumber = 9,
                            TelephoneNumber = "450576549"
                        },
                        new
                        {
                            UserId = 40,
                            Age = 1213016534,
                            FirstName = "I0EZB3BCDN1QPYZDI",
                            LastName = "NXF6WKIGD538214DMMPCVZN6Q",
                            Street = "RZVFDVQ24I",
                            StreetNumber = 24,
                            TelephoneNumber = "721435204"
                        },
                        new
                        {
                            UserId = 41,
                            Age = 1212123176,
                            FirstName = "NXGFXKIQ7TA9WRK0",
                            LastName = "KJ49HVW09HXLE1V4EA4B73J96",
                            Street = "ME4Q50FIFV9WM",
                            StreetNumber = 12,
                            TelephoneNumber = "248169486"
                        },
                        new
                        {
                            UserId = 42,
                            Age = 784720149,
                            FirstName = "5DAKF45S",
                            LastName = "5JCIN151RSGGO1ORC0VIS0BH",
                            Street = "MFCTOXDVE32OFRQPY3Q",
                            StreetNumber = 16,
                            TelephoneNumber = "621735758"
                        },
                        new
                        {
                            UserId = 43,
                            Age = 540934714,
                            FirstName = "450S19D8OVSS4",
                            LastName = "685Y4T07TF7R9KPRKZDL5KBH2Y",
                            Street = "0F1ZUYGKK3QLW2DEKKGF",
                            StreetNumber = 10,
                            TelephoneNumber = "382987021"
                        },
                        new
                        {
                            UserId = 44,
                            Age = 841211295,
                            FirstName = "OBKHDZ8DJDYMS377QWS",
                            LastName = "K388FPIEUIZ0HED6CNRUAZJ3",
                            Street = "MVR7MUVK93T6K3OT6W7Y5F",
                            StreetNumber = 22,
                            TelephoneNumber = "497964034"
                        },
                        new
                        {
                            UserId = 45,
                            Age = 404859870,
                            FirstName = "YSSG51XN07S40L2D",
                            LastName = "HHPWMS963O7O",
                            Street = "CMBYQ4SBN8EN0B5CE8YUTF",
                            StreetNumber = 26,
                            TelephoneNumber = "609931966"
                        },
                        new
                        {
                            UserId = 46,
                            Age = 609016402,
                            FirstName = "18WGSU7ZC8D2ZYXVUJJZGJBGOOU7AV",
                            LastName = "E0KO2ZY92OAXO61UOZ",
                            Street = "UNPHHF0L4SNL00M9TJCM098LR",
                            StreetNumber = 11,
                            TelephoneNumber = "460774947"
                        },
                        new
                        {
                            UserId = 47,
                            Age = 209680845,
                            FirstName = "66KQLFVXKX4GI5G0C8T65I662NMG",
                            LastName = "6ZFE4ISOVQV6JGDJ323K27D5N9X9",
                            Street = "AYQT9BOJ",
                            StreetNumber = 17,
                            TelephoneNumber = "698473960"
                        },
                        new
                        {
                            UserId = 48,
                            Age = 809381832,
                            FirstName = "T1RR2FU1OFVRQW7NNUG0ZLKS0NMPL",
                            LastName = "CFKT7GSEJWCGGNKUT9MM",
                            Street = "YLQR89VC2X8VT6B9VJ05USB",
                            StreetNumber = 19,
                            TelephoneNumber = "032124974"
                        },
                        new
                        {
                            UserId = 49,
                            Age = 1767575206,
                            FirstName = "XTE7IF4MC8AC49MZZSN53",
                            LastName = "0KJ4NWLWRIZ1XXCU1UURDR5BVHT8BM",
                            Street = "Q6DQH6Y05IK",
                            StreetNumber = 28,
                            TelephoneNumber = "477886372"
                        },
                        new
                        {
                            UserId = 50,
                            Age = 31765721,
                            FirstName = "NUENJA74I",
                            LastName = "N2LQX9EYT44L6VCEO5UQPFWFX5NOD",
                            Street = "R1MCMZWE12KL4IOHIF",
                            StreetNumber = 9,
                            TelephoneNumber = "484230982"
                        },
                        new
                        {
                            UserId = 51,
                            Age = 508100787,
                            FirstName = "FF32W0VRP97ZG",
                            LastName = "FTXMF6QL8",
                            Street = "SYLHBXSKEWBJ2R",
                            StreetNumber = 22,
                            TelephoneNumber = "280943567"
                        },
                        new
                        {
                            UserId = 52,
                            Age = 399992862,
                            FirstName = "OL9AHMSI0",
                            LastName = "9JP0RIS59N9Y9FPAV3446J",
                            Street = "3BPWT7H6HE8LI9CO7WU03HHU1XXB",
                            StreetNumber = 11,
                            TelephoneNumber = "888930651"
                        },
                        new
                        {
                            UserId = 53,
                            Age = 418318731,
                            FirstName = "YC0L3UH0YN5Z0DU7YJH5M33",
                            LastName = "9V8WEDSWFVR2CRG1365",
                            Street = "UROR0MI1",
                            StreetNumber = 26,
                            TelephoneNumber = "328385000"
                        },
                        new
                        {
                            UserId = 54,
                            Age = 1937526334,
                            FirstName = "GDPCQ8BFY1U2UAPUIKWT3F8FIKJ6",
                            LastName = "0Z1B059V4",
                            Street = "4IJMHWUWV5IUEW2",
                            StreetNumber = 28,
                            TelephoneNumber = "821640705"
                        },
                        new
                        {
                            UserId = 55,
                            Age = 918933772,
                            FirstName = "0SSDPIZROO601Z54",
                            LastName = "AYHCBYOIAHP8Z7N",
                            Street = "L3AJAAEK3GYEC8B314FQ8OQZ",
                            StreetNumber = 14,
                            TelephoneNumber = "925623996"
                        },
                        new
                        {
                            UserId = 56,
                            Age = 1416057024,
                            FirstName = "Q4PNIDW0HPNEJFACFMBT",
                            LastName = "2XUYSN860E8DWWFY6NT1AK",
                            Street = "FC9EJWXN1SJZ3D4PBJSZQ",
                            StreetNumber = 28,
                            TelephoneNumber = "368649016"
                        },
                        new
                        {
                            UserId = 57,
                            Age = 1981487916,
                            FirstName = "8KF0883HX3DG3T6WIEST3HG",
                            LastName = "LGNVZDBD54L",
                            Street = "YG4Y00X4RKPBWT5OJ8R1VR3J9XYU8",
                            StreetNumber = 11,
                            TelephoneNumber = "885950366"
                        },
                        new
                        {
                            UserId = 58,
                            Age = 852743589,
                            FirstName = "UV915RR7SCJMYSCQ",
                            LastName = "TA5R2MLT1",
                            Street = "KMMOTBO21EAO1VISU1AL8H10",
                            StreetNumber = 30,
                            TelephoneNumber = "607056094"
                        },
                        new
                        {
                            UserId = 59,
                            Age = 883794711,
                            FirstName = "I746Y1551IXIET342AY0WSWCBXNL9",
                            LastName = "4NN5YZI3O30GIH122DZXQ",
                            Street = "6XTRJS8G",
                            StreetNumber = 19,
                            TelephoneNumber = "242737803"
                        },
                        new
                        {
                            UserId = 60,
                            Age = 1178726306,
                            FirstName = "NPGLA4Q7TIVCQ5PQ4Q7QXFD7TEAH7X",
                            LastName = "ZECIP3EJU4KLBAKVRXR1SQ9KIMI15",
                            Street = "HNK4I4DV9W59PKOLI5KWMCMC7V8OQ",
                            StreetNumber = 27,
                            TelephoneNumber = "209389460"
                        },
                        new
                        {
                            UserId = 61,
                            Age = 1349119587,
                            FirstName = "ZEMG5X4ALDN7OKLTMJ",
                            LastName = "TA7X3XV7CO2W9COM26MX6V5C",
                            Street = "GNWM3B7ISTUQ6OJE1ACUMN1WK",
                            StreetNumber = 11,
                            TelephoneNumber = "786728049"
                        },
                        new
                        {
                            UserId = 62,
                            Age = 1565289725,
                            FirstName = "17F5RC39F3V2ECM9ULN2NG",
                            LastName = "ITYM8V4ZG95F2J69QZKU8B0MLSA",
                            Street = "1RTTJ02WSRN4A8TWA",
                            StreetNumber = 16,
                            TelephoneNumber = "222261938"
                        },
                        new
                        {
                            UserId = 63,
                            Age = 1556276690,
                            FirstName = "MUH056J5W8CP8JY5MFEAJZSQ",
                            LastName = "O14VRAWM6NEEGHHL9U5JVRM2",
                            Street = "NLDO2J6U0YL6CDV4H3MBQVQS71XU",
                            StreetNumber = 22,
                            TelephoneNumber = "565536070"
                        },
                        new
                        {
                            UserId = 64,
                            Age = 1002628625,
                            FirstName = "6YKEXHD6PB96OC2R0BOF0C60O72SPQ",
                            LastName = "5OYW5DTPS8UZN",
                            Street = "PJF7QCC5U1G",
                            StreetNumber = 14,
                            TelephoneNumber = "253251530"
                        },
                        new
                        {
                            UserId = 65,
                            Age = 423573934,
                            FirstName = "LZSNR2CT3ZDND0UF027NG86R4APK",
                            LastName = "UKBMWXEWFJ",
                            Street = "2U0ZPUR83ES0Q7NGW5HGNSQFPOI",
                            StreetNumber = 23,
                            TelephoneNumber = "883978069"
                        },
                        new
                        {
                            UserId = 66,
                            Age = 646005423,
                            FirstName = "TVTKTMU9ZA72M3EXUR",
                            LastName = "LLVW2KCOFR01WUR14DGLM14LSTUPWE",
                            Street = "WQ4YM3ATQM2PIPCBRC",
                            StreetNumber = 26,
                            TelephoneNumber = "455719979"
                        },
                        new
                        {
                            UserId = 67,
                            Age = 1003544836,
                            FirstName = "G4OMMMJHNUU3HCO7",
                            LastName = "XX5RJ3EO10BIO",
                            Street = "PR9ILH5BKUOFVTRJDJ0W2AZIHC3N35",
                            StreetNumber = 19,
                            TelephoneNumber = "242221119"
                        },
                        new
                        {
                            UserId = 68,
                            Age = 1798650034,
                            FirstName = "ZGA47BK7UVI98CMP95E0B",
                            LastName = "0AQ616HJUID32BONKJ6J",
                            Street = "MCIHSF2F",
                            StreetNumber = 21,
                            TelephoneNumber = "360308752"
                        },
                        new
                        {
                            UserId = 69,
                            Age = 1427244910,
                            FirstName = "V5428OPOS0BP0KVYKWVO8J",
                            LastName = "STJKWFJ0T16Z2T0HCUASTMKT0OH4X0V",
                            Street = "TGQ9OBJN0KB96FJLA",
                            StreetNumber = 23,
                            TelephoneNumber = "383270722"
                        },
                        new
                        {
                            UserId = 70,
                            Age = 9965844,
                            FirstName = "3FIN7HRS81",
                            LastName = "JS4WZFWCKIH1ZVPGA9TUK46YSV",
                            Street = "Y4V2ETOT470QFIZUI8O",
                            StreetNumber = 13,
                            TelephoneNumber = "890950149"
                        },
                        new
                        {
                            UserId = 71,
                            Age = 662234103,
                            FirstName = "1FHLWYUFR5O9E7O0BCECQM6WOE4XBL",
                            LastName = "T6Q506T9Z8W",
                            Street = "AOW5E5WOS1SBQSPHROWGDD",
                            StreetNumber = 8,
                            TelephoneNumber = "105220651"
                        },
                        new
                        {
                            UserId = 72,
                            Age = 2054394642,
                            FirstName = "F05CYCY4SC",
                            LastName = "D4M0U43UUN0BU59QRK",
                            Street = "QOJV7S46",
                            StreetNumber = 22,
                            TelephoneNumber = "480584146"
                        },
                        new
                        {
                            UserId = 73,
                            Age = 420484251,
                            FirstName = "YWHT6VTBLRLN",
                            LastName = "HNFTYAB8NO8JT3W03",
                            Street = "4CAT7WCSACYJLZOYK",
                            StreetNumber = 18,
                            TelephoneNumber = "782952214"
                        },
                        new
                        {
                            UserId = 74,
                            Age = 2099495548,
                            FirstName = "SVCCD41W3M0UW",
                            LastName = "CXAWN8A3WBV1TVFVGCH7ICGG",
                            Street = "KUGXZQ5FG0YIJLHIJM27KSBVRDJ28",
                            StreetNumber = 13,
                            TelephoneNumber = "346542783"
                        },
                        new
                        {
                            UserId = 75,
                            Age = 1113351460,
                            FirstName = "45HDKSTYHZTDFZ5CKFLKTMH5SNJ",
                            LastName = "OS5O2HWRDCGYW9",
                            Street = "CXOAIY8BRMKFRHFXNZR9R3OARNJG",
                            StreetNumber = 12,
                            TelephoneNumber = "098315912"
                        },
                        new
                        {
                            UserId = 76,
                            Age = 2043646683,
                            FirstName = "LXQ67D31SJPLZRG2VO",
                            LastName = "E98ILHZM",
                            Street = "JSXMU7JKJY3FL7DO8I9WYUGH7WBF0",
                            StreetNumber = 19,
                            TelephoneNumber = "398158316"
                        },
                        new
                        {
                            UserId = 77,
                            Age = 876240522,
                            FirstName = "AFBXFVQMPFZI1MNUNK16DADG",
                            LastName = "9T3JSD44YPJ6I98NB",
                            Street = "AVGZZHM4",
                            StreetNumber = 26,
                            TelephoneNumber = "577228139"
                        },
                        new
                        {
                            UserId = 78,
                            Age = 1236642209,
                            FirstName = "GK6DOHB94608",
                            LastName = "S4OFLYRHV1PS1ROXO0X905UQ9S7W",
                            Street = "UAB5JFBXD6B4ND7EXEL3SCITQV1LAD",
                            StreetNumber = 11,
                            TelephoneNumber = "487040615"
                        },
                        new
                        {
                            UserId = 79,
                            Age = 2135541125,
                            FirstName = "K8F214CE5WPNQ2Q21LO2KC9",
                            LastName = "5H93B0ZEKOLIPGT05P",
                            Street = "V8USRUWZWLQFD8E",
                            StreetNumber = 23,
                            TelephoneNumber = "812288647"
                        },
                        new
                        {
                            UserId = 80,
                            Age = 1242514962,
                            FirstName = "NU1X65PFKW8F7",
                            LastName = "L7T8CDJYJA5VLR64G",
                            Street = "MI807T5JDE7KDBQ",
                            StreetNumber = 12,
                            TelephoneNumber = "362899447"
                        },
                        new
                        {
                            UserId = 81,
                            Age = 1763304634,
                            FirstName = "PQ11KER7WTUKPI",
                            LastName = "PGKVY6DBHBYUTIGD85UA428AVMCEUOB",
                            Street = "KUZLZ3A1E9M8YK11KT7",
                            StreetNumber = 20,
                            TelephoneNumber = "433509233"
                        },
                        new
                        {
                            UserId = 82,
                            Age = 865655509,
                            FirstName = "FDH6UDAWHYQIJOBONYE2WXJIYO066TN",
                            LastName = "1ZQQZ25MV2XSXO8487QJMANS39IGME",
                            Street = "ZWT7ZQQWP5HDWHJAM38R2",
                            StreetNumber = 25,
                            TelephoneNumber = "635459675"
                        },
                        new
                        {
                            UserId = 83,
                            Age = 1728828246,
                            FirstName = "O6MH6QU4UTCP70QF1WH81IB999D1Y",
                            LastName = "AUPOC9V1FW950OUKX9UMLM9GF",
                            Street = "G391UKQ689CDU0L7WZUZARC9GE",
                            StreetNumber = 12,
                            TelephoneNumber = "832938185"
                        },
                        new
                        {
                            UserId = 84,
                            Age = 1031105553,
                            FirstName = "CKDLD2L6OIJYH8TTJW3P551K1LLR",
                            LastName = "L2GU2MOJ2DUD",
                            Street = "TXQTAQV85RXPYMEHMOXVII6FISJJFZ6",
                            StreetNumber = 26,
                            TelephoneNumber = "209292979"
                        },
                        new
                        {
                            UserId = 85,
                            Age = 1166331422,
                            FirstName = "RLJKD2E4PJKDJCFV6DSX",
                            LastName = "PTAWF5T2S8PPKH0G29WRK4HIFCB",
                            Street = "R9HT3T2Q3ZCPDDPWFKQTJLEX0KUNB",
                            StreetNumber = 20,
                            TelephoneNumber = "144837072"
                        },
                        new
                        {
                            UserId = 86,
                            Age = 1417095126,
                            FirstName = "FBY6I77MQCHD0LN8HHQRQG5EUP32LX",
                            LastName = "YQR8CHKJXNPAAV662",
                            Street = "7VC7K5Y94OPDD6GSUL2QD3AXDRUBVG7",
                            StreetNumber = 10,
                            TelephoneNumber = "583644915"
                        },
                        new
                        {
                            UserId = 87,
                            Age = 694174073,
                            FirstName = "A96W8QUI",
                            LastName = "GKCJYP337Q5MQ1JCX",
                            Street = "DFB3ZTWINL1773DAG5SXSBX0399",
                            StreetNumber = 15,
                            TelephoneNumber = "043075623"
                        },
                        new
                        {
                            UserId = 88,
                            Age = 862664010,
                            FirstName = "66SDXUIWUKFR1CGVTXQBOZ8AWR31",
                            LastName = "WJQQWPDGQ8XF1UXL1ET3960O",
                            Street = "8QJ5WAUPO4V",
                            StreetNumber = 21,
                            TelephoneNumber = "419541749"
                        },
                        new
                        {
                            UserId = 89,
                            Age = 1992666117,
                            FirstName = "6XEKY5NJ700TC6GIGX926Y3XWW0",
                            LastName = "51T3CVX3CW4V2RSHGRVD8P61D56H3RX",
                            Street = "YAEXCPCY",
                            StreetNumber = 9,
                            TelephoneNumber = "133119442"
                        },
                        new
                        {
                            UserId = 90,
                            Age = 778156011,
                            FirstName = "510GZPAU92QODMAKBE",
                            LastName = "VJM8Z5RBGBSBRM7LOGK23MVUB7VK",
                            Street = "T3OAOGWQEAWB",
                            StreetNumber = 27,
                            TelephoneNumber = "611974158"
                        },
                        new
                        {
                            UserId = 91,
                            Age = 72786650,
                            FirstName = "X272JGHU5PEZ6",
                            LastName = "3VF8UOTCDK7TE29CMU0HSZ5JB",
                            Street = "HO3SQ09CGAWD0LB",
                            StreetNumber = 8,
                            TelephoneNumber = "126062142"
                        },
                        new
                        {
                            UserId = 92,
                            Age = 48509856,
                            FirstName = "V8DU4ES7AIOL82X39CKSHDLC",
                            LastName = "GOOEW9FNM3WZRZ4FKDQRVVQWWDVN",
                            Street = "20WZVYX40BOV3CT8YIDZ66UIKQCXYM",
                            StreetNumber = 28,
                            TelephoneNumber = "446076717"
                        },
                        new
                        {
                            UserId = 93,
                            Age = 860499541,
                            FirstName = "V81SSN2T5M9Y2B",
                            LastName = "BSYHHY8RWS",
                            Street = "J7W8ADRNQN6A4V",
                            StreetNumber = 22,
                            TelephoneNumber = "294548440"
                        },
                        new
                        {
                            UserId = 94,
                            Age = 1712438740,
                            FirstName = "VWQF96G5CJ5GIMAK",
                            LastName = "H2L1KH4VD65TFHEFC4OMGK9Z",
                            Street = "K55QN1WAPZLNLOLX",
                            StreetNumber = 22,
                            TelephoneNumber = "347823306"
                        },
                        new
                        {
                            UserId = 95,
                            Age = 386726726,
                            FirstName = "VF80E06TUQSAV3QT90WO9OJOO93",
                            LastName = "50EEJZ0QM",
                            Street = "MWKOVU6AKL7C1AFRV8S7",
                            StreetNumber = 24,
                            TelephoneNumber = "480478401"
                        },
                        new
                        {
                            UserId = 96,
                            Age = 441298972,
                            FirstName = "NSYO9M4WM7F5IZ5TV1NN5F36SAK",
                            LastName = "EZ0J9CFLSQU8KL",
                            Street = "8VI5T4H5ULE74X3MN16D9HLI",
                            StreetNumber = 19,
                            TelephoneNumber = "764100534"
                        },
                        new
                        {
                            UserId = 97,
                            Age = 2045726725,
                            FirstName = "ULKLEE7W1VV6Z",
                            LastName = "4T2U8QRTJIT1NTWT3D3M7L6U1CX",
                            Street = "8HZ159CURWG55GUTAEHODUYCIC5J",
                            StreetNumber = 29,
                            TelephoneNumber = "256537854"
                        },
                        new
                        {
                            UserId = 98,
                            Age = 1058617481,
                            FirstName = "EELGAV6J42OMJ7B1EOB5K4GYA",
                            LastName = "G1LPZ9DX5DPKC19J2QPUUXI8SWM1QJ7",
                            Street = "21BBB1N0N9H1RDM5TXI363UJ0WBNW",
                            StreetNumber = 23,
                            TelephoneNumber = "104194042"
                        },
                        new
                        {
                            UserId = 99,
                            Age = 1308191296,
                            FirstName = "POTSN6DXLHVG2E",
                            LastName = "N4MNOAM8",
                            Street = "7L3MJ5ABZ",
                            StreetNumber = 22,
                            TelephoneNumber = "267308422"
                        },
                        new
                        {
                            UserId = 100,
                            Age = 858220949,
                            FirstName = "2UP1N8ONNSH1",
                            LastName = "OIPTESDA9G41T5FWG7N3LHHQXC3F",
                            Street = "X5WUS916OQ1TYL6BYYLIDQ7I0",
                            StreetNumber = 15,
                            TelephoneNumber = "938889969"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
